export class IdentityKtpModel {
    nik: string = '';
    name: string = '';
    birth_place_and_date: string = '';
    birth_place: string = '';
    birth_date: string = '';
    address: string = '';
    gender: string = '';
    rt_rw: string = '';
    rt: string = '';
    rw: string = '';
    village: string = '';
    subdistrict: string = '';
    religion: string = '';
    martial_status: string = '';
    work: string = '';
    province: string = '';
    city: string = '';
    nationaly: string = '';
    valid_until: string = '';
    blood_type: string = '';
}
